ALTER TABLE coupons ADD COLUMN IF NOT EXISTS per_customer_usage_limit INTEGER;
UPDATE coupons SET per_customer_usage_limit = 1 WHERE per_customer_usage_limit IS NULL;

CREATE TABLE IF NOT EXISTS admin_review_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    read_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_admin_review_reads UNIQUE (admin_user_id, review_id),
    CONSTRAINT fk_admin_review_reads_admin FOREIGN KEY (admin_user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_admin_review_reads_review FOREIGN KEY (review_id) REFERENCES reviews(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admin_review_reads_admin ON admin_review_reads(admin_user_id);
CREATE INDEX IF NOT EXISTS idx_admin_review_reads_review ON admin_review_reads(review_id);
