spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

app.seed-demo.enabled=${APP_SEED_DEMO_DATA:false}
app.seed-demo.user-email=${APP_SEED_DEMO_USER_EMAIL:customer@shopsflow.com}
app.seed-demo.user-password=${APP_SEED_DEMO_USER_PASSWORD:Customer123!}
